# See https://pre-commit.com/ for usage and config
default_language_version:
  python: python3.9
default_stages: [ commit ]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace

      - id: end-of-file-fixer
        name: Ensure newline at EOF

      - id: requirements-txt-fixer
        name: Sort requirements.txt

      - id: name-tests-test
        name: Tests should end with '_test'
        exclude: utils.py|samples/

  - repo: local
    hooks:
      - id: isort
        entry: isort
        language: system
        name: isort
        types: [ python ]

      - id: black
        name: black
        language: system
        entry: black
        types: [ python ]

      - id: flake8
        name: flake8
        language: system
        entry: flake8
        types: [ python ]
        exclude: setup.py

      - id: mypy
        name: mypy
        language: system
        entry: mypy .
        types: [ python ]
        pass_filenames: false
